const puppeteer = require('puppeteer');

class PDFService {
  constructor() {
    this.browser = null;
  }

  async initBrowser() {
    if (!this.browser) {
      this.browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
    }
    return this.browser;
  }

  async generatePDFFromHTML(htmlContent, title, userEmail = null) {
    let page = null;
    try {
      console.log(`Generating PDF for '${title}' using Puppeteer`);

      // Create a better styled HTML document
      const styledHTML = this.createStyledHTML(htmlContent, title, userEmail);

      // Initialize browser and create page
      const browser = await this.initBrowser();
      page = await browser.newPage();

      // Set content
      await page.setContent(styledHTML, { 
        waitUntil: 'networkidle0',
        timeout: 30000 
      });

      // Generate PDF with better options
      const pdfBuffer = await page.pdf({
        format: 'A4',
        margin: {
          top: '20mm',
          right: '15mm',
          bottom: '20mm',
          left: '15mm'
        },
        printBackground: true,
        preferCSSPageSize: true
      });
      
      console.log(`Successfully generated PDF: ${pdfBuffer.length} bytes`);
      return pdfBuffer;

    } catch (error) {
      console.error('Error generating PDF with Puppeteer:', error);
      throw new Error(`PDF generation failed: ${error.message}`);
    } finally {
      if (page) {
        await page.close();
      }
    }
  }

  createStyledHTML(content, title, userEmail) {
    // Convert markdown to HTML if needed
    const htmlContent = this.markdownToHTML(content);
    
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const footerText = userEmail ? `Generated by ${userEmail}` : 'Generated by CodeTutor AI';

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }

        .page {
            background: white;
            margin: 0;
            padding: 0;
            min-height: 100vh;
            position: relative;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            text-align: center;
            margin-bottom: 2rem;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }

        .header h1 {
            font-size: 2.5rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
            text-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .header .subtitle {
            font-size: 1.1rem;
            opacity: 0.9;
            font-weight: 300;
        }

        .content {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 2rem 4rem 2rem;
        }

        h1, h2, h3, h4, h5, h6 {
            font-weight: 600;
            margin-top: 2rem;
            margin-bottom: 1rem;
            color: #2d3748;
        }

        h1 { 
            font-size: 2.5rem; 
            color: #1a202c;
            border-bottom: 3px solid #667eea;
            padding-bottom: 0.5rem;
        }
        h2 { 
            font-size: 2rem; 
            color: #2d3748;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 0.3rem;
        }
        h3 { 
            font-size: 1.5rem; 
            color: #4a5568;
        }

        p {
            margin-bottom: 1.2rem;
            color: #4a5568;
            font-weight: 400;
        }

        pre {
            background: #f7fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 1.5rem;
            margin: 1.5rem 0;
            overflow-x: auto;
            font-family: 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace;
            font-size: 0.875rem;
            line-height: 1.5;
        }

        code {
            background: #edf2f7;
            color: #d63384;
            padding: 0.25rem 0.5rem;
            border-radius: 4px;
            font-family: 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace;
            font-size: 0.875rem;
        }

        pre code {
            background: none;
            color: #2d3748;
            padding: 0;
        }

        blockquote {
            border-left: 4px solid #667eea;
            background: #f8f9ff;
            padding: 1rem 1.5rem;
            margin: 1.5rem 0;
            border-radius: 0 8px 8px 0;
        }

        ul, ol {
            margin-left: 2rem;
            margin-bottom: 1.5rem;
        }

        li {
            margin-bottom: 0.5rem;
            color: #4a5568;
        }

        a {
            color: #667eea;
            text-decoration: none;
            font-weight: 500;
        }

        a:hover {
            text-decoration: underline;
        }

        .mermaid {
            text-align: center;
            margin: 2rem 0;
            padding: 1rem;
            background: #f8f9ff;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 1.5rem 0;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }

        th, td {
            padding: 1rem;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
        }

        th {
            background: #f7fafc;
            font-weight: 600;
            color: #2d3748;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-align: center;
            padding: 1rem;
            font-size: 0.875rem;
            box-shadow: 0 -2px 10px rgba(0,0,0,0.1);
        }

        .footer .divider {
            width: 50px;
            height: 2px;
            background: white;
            margin: 0.5rem auto;
            opacity: 0.5;
        }

        .footer .credits {
            font-weight: 300;
            opacity: 0.9;
        }

        .footer .date {
            font-weight: 400;
            margin-top: 0.25rem;
        }

        /* Print-specific styles */
        @media print {
            body {
                background: white;
            }
            
            .page {
                margin: 0;
                padding: 0;
            }
            
            .footer {
                position: fixed;
                bottom: 0;
            }
        }

        /* Page break utilities */
        .page-break {
            page-break-before: always;
        }

        .no-page-break {
            page-break-inside: avoid;
        }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <h1>${title}</h1>
            <div class="subtitle">Comprehensive Tutorial & Documentation</div>
        </div>
        
        <div class="content">
            ${htmlContent}
        </div>
        
        <div class="footer">
            <div class="divider"></div>
            <div class="credits">${footerText}</div>
            <div class="date">${currentDate}</div>
        </div>
    </div>
</body>
</html>`;
  }

  markdownToHTML(markdown) {
    // Simple markdown to HTML conversion
    // You might want to use a proper markdown library like marked
    let html = markdown
      // Headers
      .replace(/^### (.*$)/gm, '<h3>$1</h3>')
      .replace(/^## (.*$)/gm, '<h2>$1</h2>')
      .replace(/^# (.*$)/gm, '<h1>$1</h1>')
      // Bold and italic
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      // Code blocks
      .replace(/```([^`]+)```/gs, '<pre><code>$1</code></pre>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // Links
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
      // Line breaks
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');

    // Wrap in paragraphs
    html = '<p>' + html + '</p>';
    
    // Clean up empty paragraphs
    html = html.replace(/<p>\s*<\/p>/g, '');
    
    return html;
  }
}

module.exports = PDFService;